on:
  push:
    branches:
      - master







jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Login to Docker Hub"
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}

      - name: "Build and push Docker images"
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myimage .


      - name: "Build and push Docker images"
        run: docker push ${{ secrets.DOCKER_USERNAME }}/myimage
